# Constantes de localização
uint32 NORTE = 0
uint32 SUL = 1 
uint32 LESTE = 2
uint32 OESTE = 3
# Equivalentes às acima
uint32 ORIENTATION_TREM = 0
uint32 ORIENTATION_INICIO = 1
uint32 ORIENTATION_AZUL = 2
uint32 ORIENTATION_VERDE = 3
# Constantes de localização
uint32 QUADRANTE_CENTRAL=0
uint32 QUADRANTE_ESQUERDO=1
uint32 QUADRANTE_DIREITO=2
uint32 DOCA_VERDE=3
uint32 DOCA_AZUL=4
uint32 DOCA_CENTRAL=5
uint32 TREM=6
# Mensagem com localização e orientação
uint32 location
uint32 orientation
#Quantidade de containers depositados
uint32 code
