#Posição
projeto_semear/Pose Posicao

---
#qual container escolhi:

uint8 container_escolhido # 0=esquerda, 1 = direita, 2 = só tem vermelho aqui
uint8 cor # 13=azul, 12=verde, 14=vermelho //mudar aqui para a .msg
uint8 pilha #posição da pilha que pegou


